# Publish this application to bluemix using ansible
---
- name: Publish the app to AWS
  hosts: localhost
  connection: local
  vars:
    app_name: "{{ lookup('env','APP_NAME') }}"
    s3_bucket: "{{ lookup('env', 'S3_BUCKET') | default(app_name,true) }}"
    region: "{{ lookup('env', 'AWS_DEFAULT_REGION') | default('us-west-2', true) }}"
    solution_stack_name: "64bit Amazon Linux 2016.09 v2.5.3 running Tomcat 8 Java 8"

  tasks:
    # ------------------------------------------------------------
    # Set Facts
    # ---
    # Store datetime for version info
    - name: Create version string
      set_fact:
        version: "{{ lookup('pipe', 'date +%Y%m%d-%H%M%S%Z')  }}"

    # Create information for archive zip
    - name: Create Artifact information
      set_fact:        
        zip_filename: "target/spring-petclinic-1.4.2.war"
        zip_dir: "{{ lookup('env', 'PWD') }}/target"
      
    # ------------------------------------------------------------
    # AWS Deploy
    # ---
    - name: push to s3
      s3:
        mode: put
        region: "{{ region }}"
        bucket: "{{ s3_bucket }}"
        src: "{{ zip_dir }}/{{ zip_filename }}"
        object: "{{ zip_filename }}"
        
    # ansible elastic beanstalk: https://github.com/hsingh/ansible-elastic-beanstalk
    # Create beanstalk app
    - name: Create Elastic Beanstalk application
      elasticbeanstalk_app:
        region: "{{ region }}"
        app_name: "{{ app_name }}"
        state: present
      register: app_output

    # Connect to s3 bucket version
    - name: Link uploaded version
      elasticbeanstalk_version:
        region: "{{ region }}"
        app_name: "{{ app_name }}"
        version_label: "{{ version }}"
        s3_bucket: "{{ s3_bucket  }}"
        s3_key: "{{zip_filename}}"
        state: present
      register: version_output

    # Create the environment
    - name: Create app env
      elasticbeanstalk_env:
        region: "{{ region }}"
        app_name: "{{ app_name }}"
        env_name: "{{ app_name }}-env"
        version_label: "{{ version }}"
        solution_stack_name: "{{ solution_stack_name }}"
      register: env_output
# ------------------------------------------------------------
